// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Script, console } from "forge-std/Script.sol";
import { Groth16Verifier as Verifier } from "../src/Verifier.sol";
import { DKIMRegistry }     from "../src/DKIMRegistry.sol";
import { AttestationCache } from "../src/AttestationCache.sol";

/// @notice Deploys the full Signet stack to any EVM network.
///
/// Usage (Base Sepolia — recommended):
///   forge script script/Deploy.s.sol \
///     --rpc-url base_sepolia \
///     --account <keystore-name> \
///     --broadcast \
///     --verify \
///     -vvvv
///
///   The --account flag uses a Foundry encrypted keystore (cast wallet import).
///   It prompts for a password at runtime — no private key in env files.
///   See: https://book.getfoundry.sh/reference/cast/cast-wallet-import
///
/// Env vars:
///   DKIM_PUBKEY_HASH  — (optional) initial pubkey hash to register at deploy time.
///                       Find it from pubSignals[0] after running:
///                       node circuits/scripts/prove.mjs <email.eml>
///                       If not set, register keys later via dkimRegistry.setKey().
///
/// Output:
///   ./deployments/<network>.json  — written automatically after a successful run.
contract DeploySignet is Script {

    function run() external {
        string memory network = vm.envOr("NETWORK", string("base_sepolia"));

        vm.startBroadcast();

        // 1. Deploy Groth16 verifier (generated by snarkjs).
        Verifier verifier = new Verifier();
        console.log("Verifier:        ", address(verifier));

        // 2. Deploy DKIM registry.
        DKIMRegistry dkimRegistry = new DKIMRegistry();
        console.log("DKIMRegistry:    ", address(dkimRegistry));

        // 3. Optionally seed the registry with a known pubkey hash.
        uint256 initialHash = vm.envOr("DKIM_PUBKEY_HASH", uint256(0));
        if (initialHash != 0) {
            dkimRegistry.setKey(initialHash, true);
            console.log("Registered hash: ", initialHash);
        }

        // 4. Deploy AttestationCache — no cutoff; downstream airdrop contracts
        //    apply their own date logic via getAttestation().emailTimestamp.
        AttestationCache cache = new AttestationCache(
            address(verifier),
            address(dkimRegistry)
        );
        console.log("AttestationCache:", address(cache));

        vm.stopBroadcast();

        // Write deployment addresses to a JSON file for the frontend and CI/CD.
        string memory obj = "signet_deployment";
        vm.serializeAddress(obj, "NEXT_PUBLIC_VERIFIER",          address(verifier));
        vm.serializeAddress(obj, "NEXT_PUBLIC_DKIM_REGISTRY",     address(dkimRegistry));
        string memory json = vm.serializeAddress(obj, "NEXT_PUBLIC_ATTESTATION_CACHE", address(cache));

        string memory outPath = string.concat("./deployments/", network, ".json");
        vm.writeJson(json, outPath);
        console.log("Addresses written to", outPath);
    }
}
