/**
 * verify.mjs
 *
 * Verifies the proof generated by prove.mjs.
 *
 * Usage:
 *   node scripts/verify.mjs
 *
 * Reads:
 *   circuits/artifacts/verification_key.json
 *   circuits/build/proof.json
 *   circuits/build/public_signals.json
 */

import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dir  = dirname(fileURLToPath(import.meta.url));
const root   = resolve(__dir, "..");

const snarkjs = await import(resolve(root, "node_modules/snarkjs/build/main.cjs"));

const vkey          = JSON.parse(readFileSync(resolve(root, "artifacts/verification_key.json")));
const proof         = JSON.parse(readFileSync(resolve(root, "build/proof.json")));
const publicSignals = JSON.parse(readFileSync(resolve(root, "build/public_signals.json")));

console.log("Verifying proof…");
const valid = await snarkjs.groth16.verify(vkey, publicSignals, proof);

if (valid) {
    console.log("✓ Proof is VALID");
    // Outputs first ([0..1]), then public input ([2]) — matches Circom/snarkjs ordering.
    const labels = ["pubkeyHash", "email_timestamp", "proverETHAddress"];
    publicSignals.forEach((v, i) => {
        const label = labels[i] ?? `[${i}]`;
        let extra = "";
        if (label === "email_timestamp") {
            const ts = Number(v);
            extra = ` → ${new Date(ts * 1000).toISOString().split("T")[0]}`;
        }
        console.log(`  [${i}] ${label.padEnd(20)} ${v}${extra}`);
    });
} else {
    console.error("✗ Proof is INVALID");
    process.exit(1);
}
